### ISSUE TITLE
Atualização para o django 1.4?

### ISSUE THREAD

**Issue by gladson** [marinho/aprendendo-django#1]
Por acaso pode ser feito a atualização do aprendendo django para o django 1.4 ou 1.3?
E mandado um Pull Requests?
:D

É claro sem mudar a didática e as primissas do projeto em si.

**Comment by marinho** [comment]
Sim Gladson, há alguns meses atrás eu expliquei sobre isso na Django-Brasil :)

você pode dar fork e modificar, depois vai mandando pull requests que eu aceito com todo prazer. Quando tiver uma versão bacana, soltamos release :)

**Comment by gladson** [comment]
Blz... 
Valew, Marinho...
